- name: Installs strongswan & ikev2 daemon
  apt: name={{ item }} state=present
  with_items:
    - strongswan
    - strongswan-ike
    - strongswan-ikev2
  tags: apt

- name: Creates config and secrets fragments directory
  file: path=/etc/{{ item }} state=directory mode=750 owner=root
  with_items:
    - ipsec.conf.d
    - ipsec.secrets.d

- name: Creates base config
  template: src={{ item }}.j2 dest=/etc/{{ item }}
  notify: Restart strongswan
  with_items:
    - ipsec.conf
    - ipsec.secrets

- name: Adds ipsec defaults
  template: src=00_defaults.conf.j2 dest=/etc/ipsec.conf.d/00_defaults.conf
  notify: Restart strongswan

- name: Adds strongswan defaults
  template: src=01_charon.conf.j2 dest=/etc/strongswan.d/01_charon.conf
  notify: Restart strongswan

- name: Adds sysctl entry for ipforward
  sysctl: >
    name="net.ipv4.ip_forward"
    value=1
    sysctl_set=yes
    sysctl_file=/etc/sysctl.d/50_ipforward.conf
