- name: Installs strongswan & ikev2 daemon
  apt: name={{ item }} state=present
  with_items:
    - strongswan
    - strongswan-ike
    - strongswan-ikev2
  tags: apt

- name: Creates fragments config directory
  file: path=/etc/ipsec.conf.d/ state=directory mode=755 owner=root

- name: Creates base config
  template: src=ipsec.conf.j2 dest=/etc/ipsec.conf

